---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 24857.
--- DateTime: 2025/3/4 18:51
---


--- 1.参数列表
--- 1.1 优惠券id
local voucherId = ARGV[1]
---1.2用户id
local userId = ARGV[2]
---1.3订单id
local orderId = ARGV[3]
---2.数据key
---2.1库存key
local stockKey = 'voucher:stock:'.. voucherId
---2.2订单表key
local orderKey = 'voucher:order:' ..voucherId

---3.脚本业务
---3.1判断库存是否充足
if(tonumber(redis.call('get',stockKey))<=0) then
    ---3.2库存不足
    return 1
end
---3.2判断用户是否已经抢购过 集合中 sismember判断是否存在
if(redis.call('sismember',orderKey,userId) == 1) then
    return 2;
end
---3.4扣库存 incrby stockKey -1
redis.call('incrby',stockKey,-1)
---3.5下单
redis.call('sadd',orderKey,userId)
---3.6发送消息到stream消息队列中 XADD stream.orders * k1 v1 k2 v2 ...
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0